namespace ZeroInputs;
public enum Key
{
    LeftMouseButton,
    RightMouseButton,
    ControlBreak,
    MiddleMouseButton,
    X1MouseButton,
    X2MouseButton,
    Backspace,
    Tab,
    Clear,
    Enter,
    Shift,
    Control,
    Alt,
    Pause,
    CapsLock,
    IMEKana,
    IMEHangul,
    IMEOn,
    IMEJunja,
    IMEFinal,
    IMEHanja,
    IMEKanji,
    IMEOff,
    Escape,
    Space,
    PageUp,
    PageDown,
    End,
    Home,
    LeftArrow,
    UpArrow,
    RightArrow,
    DownArrow,
    Select,
    Print,
    Execute,
    PrintScreen,
    Insert,
    Delete,
    Help,
    Key0,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    LeftWindows,
    RightWindows,
    Apps,
    Sleep,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    Multiply,
    Add,
    Separator,
    Subtract,
    Decimal,
    Divide,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    NumLock,
    ScrollLock,
    LeftShift,
    RightShift,
    LeftControl,
    RightControl,
    LeftAlt,
    RightAlt,
    BrowserBack,
    BrowserForward,
    BrowserRefresh,
    BrowserStop,
    BrowserSearch,
    BrowserFavorites,
    BrowserHome,
    VolumeMute,
    VolumeDown,
    VolumeUp,
    MediaNextTrack,
    MediaPrevTrack,
    MediaStop,
    MediaPlayPause,
    LaunchMail,
    LaunchMediaSelect,
    LaunchApp1,
    LaunchApp2,
    OEMSemicolon,       // For the US standard keyboard, the ;: key
    OEMPlus,            // For any country/region, the + key
    OEMComma,           // For any country/region, the , key
    OEMMinus,           // For any country/region, the - key
    OEMPeriod,          // For any country/region, the . key
    OEMQuestion,        // For the US standard keyboard, the /? key
    OEMTilde,           // For the US standard keyboard, the `~ key
    OEMOpenBracket,     // For the US standard keyboard, the [{ key
    OEMBackslash,       // For the US standard keyboard, the \| key
    OEMCloseBracket,    // For the US standard keyboard, the ]} key
    OEMQuotes,          // For the US standard keyboard, the '" key
    OEMMisc,            // Used for miscellaneous characters; it can vary by keyboard.
    OEMPLUS102,         // The <> keys on the US standard keyboard, or the \| key on the non-US 102-key keyboard
    IMEProcess,         // IME PROCESS key
    Packet,             // Used to pass Unicode characters as if they were keystrokes
    PA1,                // PA1 key
    OEMClear,           // Clear key
}
